#include "matrix.h"
using namespace std;

// do not edit this file

int main(int argc, char **argv) {
    int n, m, p;
    cin >> n >> m >> p;
    Matrix* A = new Matrix(n,m);
    Matrix* B = new Matrix(m,p);
    A->inputMatrix();
    B->inputMatrix();
    Matrix* C = A->multiplyMatrix(B);
    C->displayMatrix();
    A->~Matrix();
    B->~Matrix();
    C->~Matrix();
    return 0;
}